version: '3.3'
networks:
  blockchain-in-compose:
    driver: bridge
volumes:
  postgres-data:
services:
  ganache:
    command: --accounts 10 --db_path /blockdata --seed "your-seed-phrase-here" --hardfork petersburg
    ports:
      - '8545:8545'
    image: 'trufflesuite/ganache:rc'
    volumes:
      - ./blockdata:/blockdata
  blockscout:
    command: /bin/sh -c "mix do ecto.create, ecto.migrate; mix phx.server"
    ports:
      - '4000:4000'
    image: 'heronimus/blockscout:devnet'
    environment:
      MIX_ENV: prod
      DATABASE_URL: postgresql://postgres:@172.17.0.1:5432/explorer?ssl: false
      ETHEREUM_JSONRPC_VARIANT: ganache
      ETHEREUM_JSONRPC_HTTP_URL: http://172.17.0.1:8545
      ETHEREUM_JSONRPC_WS_URL: ws://172.17.0.1:8545
      COIN: POO
      MIX_HOME: /opt/mix
      HEX_HOME: /opt/hex
      PORT: 4000
      SECRET_KEY_BASE: XXXXX-YOUR-SECRET-KEY-BASE
  postgres:
    command: postgres
    ports:
      - '5432:5432'
    image: 'postgres:12.5'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      PG_MAJOR: 12
      PG_VERSION: 12.5-1.pgdg100+1
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres-data:/var/lib/postgresql/data
